version: '3'

services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379 
      - REDIS_HOST=redis

  redis:
    image: "redis:alpine"
    expose:
      - "6379" 
