# Generated by Django 5.0.7 on 2024-07-18 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_classsetting_class_membership_class_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="setting",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="main.classsetting"
            ),
        ),
    ]
