# Generated by Django 5.0.7 on 2024-07-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_classfiles_classwork_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="title",
            field=models.CharField(default="", max_length=240),
            preserve_default=False,
        ),
    ]
