# Generated by Django 5.0.7 on 2024-07-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_assignment_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="code",
            field=models.CharField(default="", max_length=90),
            preserve_default=False,
        ),
    ]
