# Generated by Django 5.0.7 on 2024-07-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_assignment_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="options",
            field=models.JSONField(default=[], null=True),
        ),
    ]
