# Generated by Django 5.0.7 on 2024-07-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_assignment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classwork",
            name="date_due",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
