# Generated by Django 5.0.7 on 2024-07-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_classwork_date_due"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classwork",
            name="object_id",
            field=models.CharField(max_length=8),
        ),
    ]
