# Generated by Django 5.0.7 on 2024-07-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_anouncement_topic_topicupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicupdate",
            name="title",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
    ]
