# Generated by Django 5.0.7 on 2024-07-25 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_topicupdate_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicupdate",
            name="_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_update",
                to="main.class",
            ),
        ),
    ]
