# Generated by Django 5.0.7 on 2024-07-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_worksubmitions"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksubmitions",
            name="marked",
            field=models.BooleanField(default=False),
        ),
    ]
