# Generated by Django 4.2.3 on 2024-08-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_assignment__files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anouncement',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
