# Generated by Django 4.2.3 on 2024-08-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_topic_options_anouncement_my_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anouncement',
            old_name='my_admin',
            new_name='by_admin',
        ),
    ]
