# Generated by Django 4.2.3 on 2024-08-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_rename_my_admin_anouncement_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='anouncement',
            name='_type',
            field=models.CharField(default='stream', max_length=120),
        ),
    ]
