# Generated by Django 5.0.7 on 2024-07-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.CharField(default="", max_length=90),
            preserve_default=False,
        ),
    ]
