# Generated by Django 5.0.7 on 2024-07-18 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_user_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_can_post", models.BooleanField(default=False)),
                ("student_can_comment", models.BooleanField(default=True)),
                ("default_grade", models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("data_created", models.DateField(auto_now_add=True)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=90)),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="class/covers"),
                ),
                ("class_code", models.CharField(max_length=12)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_class",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "setting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.classsetting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberShip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_joined", models.DateField(auto_now=True)),
                (
                    "_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_membership",
                        to="main.class",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="class",
            name="members",
            field=models.ManyToManyField(
                null=True, related_name="members", to="main.membership"
            ),
        ),
    ]
