# Generated by Django 5.0.7 on 2024-07-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_classwork_object_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="_files",
        ),
        migrations.AddField(
            model_name="assignment",
            name="_files",
            field=models.JSONField(default=[]),
        ),
    ]
