# Generated by Django 5.0.7 on 2024-07-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_assignment__class"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="draft",
            field=models.BooleanField(default=False),
        ),
    ]
