# Generated by Django 5.0.7 on 2024-08-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_alter_classchat__class_alter_classchat_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classchat",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
