# Generated by Django 5.0.7 on 2024-08-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_classfiles_user_alter_classfiles__class"),
    ]

    operations = [
        migrations.AddField(
            model_name="classfiles",
            name="name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
