# Generated by Django 5.0.7 on 2024-08-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_classfiles_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="classfiles",
            name="code",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
