# Generated by Django 4.2.3 on 2024-08-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_classsetting_use_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="_files",
            field=models.JSONField(default=list, null=True),
        ),
    ]
