# Generated by Django 4.2.3 on 2024-08-18 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_anouncement_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='anouncement',
            name='my_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anouncement',
            name='title',
            field=models.CharField(default='', max_length=220),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anouncement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
