# Generated by Django 4.2.3 on 2024-09-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_activationscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.CharField(default='public', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='recieve_email',
            field=models.BooleanField(default=True),
        ),
    ]
